export default {
    background: require('../assets/background.png'),
    computer: require('../assets/computer.png'),
    discoveryVietNam: require('../assets/backgr1.jpg'),
    test: require('../assets/gallery.png'),
    hotel: require('../assets/hotel.png'),
    flight: require('../assets/flight.png'),
    train: require('../assets/train.png'),
    restaurant: require('../assets/restaurant.png'),
    restaurant1: require('../assets/restaurant1.png'),
    background1: require('../assets/background1.jpg'),
    onboarding1: require('../assets/onboarding1.jpg'),
    onboarding2: require('../assets/onboarding2.jpg'),
    onboarding3: require('../assets/onboarding3.jpg'),
    onboarding4: require('../assets/onboarding4.jpg'),
    muongthanh: require('../assets/muongthanh.jpg'),
    muongthanhbackground: require('../assets/muongthanhbackground.jpg'),
    marina: require('../assets/marina.png'),
    marinabackground: require('../assets/marinabackground.jpg'),
    vinpear: require('../assets/vinpear.jpg'),
    vinpearbackground: require('../assets/vinpearbackground.jpg'),
    seraton: require('../assets/seraton.jpeg'),
    seratonbackground: require('../assets/seratonbackground.jpg'),
    vn: require('../assets/VN.jpg'),
    nonAvatar: require('../assets/nonavatar.jpg'),
    flight1: require('../assets/maybay.jpg'),
    car1: require('../assets/xe.jpg'),
}